In [45]:
import pandas as pd
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import warnings as wr
wr.filterwarnings('ignore')



In [46]:
df = pd.read_csv('weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [47]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [48]:
df.Gender = le.fit_transform(df[['Gender']])

In [49]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [50]:
df.tail()

Gender     Height      Weight
8550       0  60.483946  110.565497
8551       0  63.423372  129.921671
8552       0  65.584057  155.942671
8553       0  67.429971  151.678405
8554       0  60.921791  131.253738

In [51]:
x = df[['Gender', 'Height']]
y = df['Weight']

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [54]:
from sklearn.linear_model import LinearRegression

In [55]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [56]:
y_train_lr_pred = lr.predict(x_train)
y_train_lr_pred

array([178.35427565, 202.22486558, 129.22191775, ..., 139.34406368,
       187.17224616, 158.78183812])

In [57]:

y_test_lr_pred = lr.predict(x_test)
y_test_lr_pred

array([142.44868114, 186.0517281 , 198.42283706, ..., 102.94080643,
       190.83713617, 143.34786753])

In [58]:
from sklearn.metrics import r2_score

In [59]:
train_ac_lr = lr.score(x_train, y_train)
train_ac_lr

0.8973793060969246

In [60]:
train_ac_lr_r2 = r2_score(y_train, y_train_lr_pred)
train_ac_lr_r2

0.8973793060969246

In [61]:
test_ac_lr = lr.score(x_test, y_test)
test_ac_lr

0.905911242442266

In [62]:
test_ac_lr_r2 = r2_score(y_test, y_test_lr_pred)
test_ac_lr_r2

0.905911242442266

In [63]:
test_ac_lr_r2 = r2_score(y_test, y_test_lr_pred)
test_ac_lr_r2


0.905911242442266

In [64]:
from sklearn.metrics import mean_squared_error

In [65]:

mse_test_lr = mean_squared_error(y_test, y_test_lr_pred)
mse_test_lr

96.83734437830608

In [66]:
from sklearn.neighbors import KNeighborsRegressor

In [67]:
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(x_train, y_train)

KNeighborsRegressor()

In [68]:
y_train_knn_pred = knn.predict(x_train)
y_train_knn_pred

array([176.58174146, 205.54968066, 129.31875904, ..., 142.55470934,
       192.1316955 , 162.1670885 ])

In [69]:
y_test_knn_pred = knn.predict(x_test)
y_test_knn_pred

array([142.1445657 , 181.38276924, 187.07075266, ..., 101.79654426,
       192.43702356, 145.3632227 ])

In [70]:
train_ac_knn = knn.score(x_train, y_train)
train_ac_knn

0.9172142723737918

In [71]:
train_ac_knn_r2 = r2_score(y_train, y_train_knn_pred)
train_ac_knn_r2

0.9172142723737918

In [72]:
test_ac_knn = knn.score(x_test, y_test)
test_ac_knn

0.8821086423439015

In [73]:
test_ac_knn_r2 = r2_score(y_test, y_test_knn_pred)
test_ac_knn_r2

0.8821086423439015

In [74]:
mse_test_knn = mean_squared_error(y_test, y_test_knn_pred)
mse_test_knn

121.33528273624482

In [75]:
print("Linear Regression:")
print("training accuracy:", train_ac_lr_r2)
print("testing accuracy:", test_ac_lr_r2)
print("testing MSE:", mse_test_lr)

Linear Regression:
training accuracy: 0.8973793060969246
testing accuracy: 0.905911242442266
testing MSE: 96.83734437830608


In [76]:
print("KNN:")
print("training accuracy:", train_ac_knn_r2)
print("testing accuracy:", test_ac_knn_r2)
print("testing MSE:", mse_test_knn)


KNN:
training accuracy: 0.9172142723737918
testing accuracy: 0.8821086423439015
testing MSE: 121.33528273624482


In [77]:
x1 = df[['Height', 'Weight']]
y1 = df['Gender']
x1.head()
y1.head()

0    1
1    1
2    1
3    1
4    1
Name: Gender, dtype: int32

In [78]:
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size = 0.3, random_state = 42)

In [79]:
from sklearn.neighbors import KNeighborsClassifier

In [80]:
knnC = KNeighborsClassifier(n_neighbors=5)
knnC.fit(x1_train, y1_train)

KNeighborsClassifier()

In [81]:
y_train_knnC_pred = knnC.predict(x1_train)
y_train_knnC_pred

array([1, 1, 0, ..., 1, 1, 0])

In [82]:
y_test_knnC_pred = knnC.predict(x1_test)
y_test_knnC_pred

array([0, 1, 1, ..., 0, 1, 0])

In [83]:
from sklearn.metrics import accuracy_score

In [84]:
train_ac_knnC = knnC.score(x1_train, y1_train)
train_ac_knnC

0.9291917167668671

In [85]:
train_ac2_knnC = accuracy_score(y1_train, y_train_knnC_pred)
train_ac2_knnC

0.9291917167668671

In [86]:
test_ac_knnC = knnC.score(x1_test, y1_test)
test_ac_knnC

0.9131281651733542

In [87]:
test_ac2_knnC = accuracy_score(y1_test, y_test_knnC_pred)
test_ac2_knnC

0.9131281651733542

In [88]:
print("training accuracy:", train_ac_knnC)
print("testing accuracy:", test_ac_knnC)

training accuracy: 0.9291917167668671
testing accuracy: 0.9131281651733542
